In [1]:
def tambah1(): # function void
    a = 20
    b = 30
    hasil = a + b
    print(hasil)

def tambah2(a, b): # function parameter
    hasil = a + b
    print(hasil)

def tambah3(a, b): # function return
    hasil = a + b
    return hasil

tambah1()   # function void
tambah2(10,20)  # function parameter
total = tambah3(40,50) # function return
print(total)

50
30
90


In [13]:
nilai = 100

def ganti():  
    global nilai
    nilai = 200

print(nilai)
ganti()
print(nilai)

100
200


FUNCTION RECURSIVE

In [42]:
def test(n): 
    if n == 0:
        return True
    else:
        return n * test(n - 1) # 10 * 9 * 3 * 2 * 1

test(5)

120

ASSIGNMENT

In [44]:
data = [90,80,100,20]

print(max(data))
print(min(data))

100
20


FUNCTION ARGS & KWARGS

In [48]:
test = [1,2,3] # list
test2 = {10,20,30} # set
test3 = (90,9,8) # tuple

test[0] = 10
print(test)

print(test3[0])

[10, 2, 3]
90


In [50]:
def tampil(*a): # args
    print(a)
    for i in a:
        print(i)

tampil("satu", "dua", "tiga")

('satu', 'dua', 'tiga')
satu
dua
tiga


In [53]:
def tampil2(**a): # kwargs
    print(a)
    for key in a.keys():
        print(a[key])

tampil2(nama="agung", alamat="denpasar")

{'nama': 'agung', 'alamat': 'denpasar'}
agung
denpasar


NUMPY

In [55]:
import numpy as np

a = np.array([1,2,3,4]) # 1 dimensi
print(a)
print(a[0])
print(a[1])

[1 2 3 4]
1
2


In [59]:
b = np.array([  # 2 dimensi
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(b)
print(b[0])
print(b[0][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
3


In [64]:
c = np.array([
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [20,21,22],
        [23,24,25],
        [26,27,28]
    ],
])

print(c)
print(c[0])
print(c[0][0])
print(c[0][1][2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
6


In [65]:
b = np.array([  # 2 dimensi
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(b.shape)
print(b.ndim)
print(b.size)

(3, 3)
2
9


INDEXING & SLICING

In [83]:
a = np.array([  
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a[1:, 0:2])

[[4 5]
 [7 8]]


In [87]:
a = np.array([  
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

a[0][1] = 20
print(a[0:, 0:2]) # [baris, kolom]

[[ 1 20]
 [ 4  5]
 [ 7  8]]


ASSIGNMENT

satu

In [89]:
# No1
data = np.array([
    ["Denis", "Scratch", 8],
    ["Frank", "Python", 18],
    ["Roger", "Unity", 15]
])

# No2
print(data[0])
print(data[1])
print(data[2])

# No3
print(data[0:, 0])
print(data[0:, 1])

# No4
data[0][1] = "Roblox"
print(data)

['Denis' 'Scratch' '8']
['Frank' 'Python' '18']
['Roger' 'Unity' '15']
['Denis' 'Frank' 'Roger']
['Scratch' 'Python' 'Unity']
[['Denis' 'Roblox' '8']
 ['Frank' 'Python' '18']
 ['Roger' 'Unity' '15']]


dua

In [105]:
# No1
data = np.array([
    ["Java", "Richie", 60, "C"],
    ["Python", "Niels", 80, "A"],
    ["R", "Brie", 75, "B"]
])

# No2
print(data[0])
print(data[1])
print(data[2])

# No3
print(data[0:, 0])
print(data[0:, 1])
print(data[0:, 2])
print(data[0:, 3])

# No4
print(data[0:2, 2:])

# No5
data[0:, 0] = "Data analyst"
print(data)

# No6
data[2][2] = 90
data[2][3] = "A+"
print(data)


['Java' 'Richie' '60' 'C']
['Python' 'Niels' '80' 'A']
['R' 'Brie' '75' 'B']
['Java' 'Python' 'R']
['Richie' 'Niels' 'Brie']
['60' '80' '75']
['C' 'A' 'B']
[['60' 'C']
 ['80' 'A']]
[['Data analyst' 'Richie' '60' 'C']
 ['Data analyst' 'Niels' '80' 'A']
 ['Data analyst' 'Brie' '75' 'B']]
[['Data analyst' 'Richie' '60' 'C']
 ['Data analyst' 'Niels' '80' 'A']
 ['Data analyst' 'Brie' '90' 'A+']]


In [103]:
data = np.array([
    ["Java", "Richie", 60, "C"],
    ["Python", "Niels", 80, "A"],
    ["R", "Brie", 75, "B"]
])

print(data[0:2, 2:]) # [baris(start : batas), kolom(start : batas)]

[['60' 'C']
 ['80' 'A']]
